version: '3.7'
services:
    db:        
        build: ./db
        container_name: "db"                    
        ports:
            - "${MYSQL_MAPPED_PORT}:3306"    
        networks: 
            graphite_net:  
    memcached:
        image: "memcached"
        container_name: "memcached"
        ports:
             - "${MEMCACHED_MAPPED_PORT}:11211"
        networks:
            graphite_net:
    composer:
        image: "composer"
        container_name: "composer"
        volumes:
            - ${GRAPHITE_CODE}:/var/www/html      
        networks:
            graphite_net:
    blogdb:
        image: "mysql:5.7"
        container_name: "blogdb"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_BLOG_ROOT_PWD}
            MYSQL_USER: ${MYSQL_BLOG_USER}
            MYSQL_PASSWORD: ${MYSQL_BLOG_PWD}
            MYSQL_DATABASE: ${MYSQL_BLOG_DATABASE}
        ports:
            - "${MYSQL_BLOG_MAPPED_PORT}:3306"
        networks:
            graphite_net:
    
    php:
        build: ./php  
        container_name: "php"              
        networks: 
            graphite_net:
        ports: 
            - "${FPM_MAPPED_PORT}:8000"
            - "${XDEBUG_MAPPED_PORT}:9000"
        volumes:
            - gfiles:/var/www/files
            - ${GRAPHITE_CODE}:/var/www/html
    apache:
        build: ./apache
        container_name: "apache"         
        ports:
            - "8080:80"      
            - "8000:8000"      
        volumes:
            - gfiles:/var/www/files
            - ${GRAPHITE_CODE}:/var/www/html      
        networks: 
            graphite_net:
        depends_on:
            - db       
            - php
            - memcached      
networks:
    graphite_net:        
volumes:
    gfiles:
