version: '3.7'
services:
    mysql:        
        build: ./mysql
        container_name: "mysql"                     
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PWD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ${MYSQL_DATA_DIR}:/var/lib/mysql
        ports:
            - "${MYSQL_MAPPED_PORT}:3306"    
        networks: 
            graphite_net:  
    memcached:
        image: "memcached"
        container_name: "memcached"
        networks:
            graphite_net:
    composer:
        image: "composer"
        container_name: "composer"
        volumes:
            - ${GRAPHITE_CODE}:/var/www/html      
        networks:
            graphite_net:
    blogdb:
        build: ./blog        
        container_name: "blogdb"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_BLOG_ROOT_PWD}
            MYSQL_USER: ${MYSQL_BLOG_USER}
            MYSQL_PASSWORD: ${MYSQL_BLOG_PWD}
            MYSQL_DATABASE: ${MYSQL_BLOG_DATABASE}
        ports:
            - "${MYSQL_BLOG_MAPPED_PORT}:3306"
        networks:
            graphite_net:
    apache:
        build: ./apache
        container_name: "apache"         
        ports:
            - "${WEB_MAPPED_PORT}:80"
        volumes:
            - ${GRAPHITE_FILES_DIR}:/var/www/files
            - ${GRAPHITE_CODE}:/var/www/html
        networks: 
            graphite_net:
        depends_on:
            - mysql
            - memcached      
networks:
    graphite_net:
