version: '3.7'
services:
    mysql:        
        build: ./mysql
        container_name: "mysql"                    
        ports:
            - "${MYSQL_MAPPED_PORT}:3306"   
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PWD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}        
        networks: 
            graphite_net:  
    memcached:
        image: "memcached"
        container_name: "memcached"
        networks:
            graphite_net:
    composer:
        image: "composer"
        container_name: "composer"
        volumes:
            - ${GRAPHITE_CODE}:/var/www/html      
        networks:
            graphite_net:
    blogdb:
        image: "mysql:5.7"
        container_name: "blogdb"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_BLOG_ROOT_PWD}
            MYSQL_USER: ${MYSQL_BLOG_USER}
            MYSQL_PASSWORD: ${MYSQL_BLOG_PWD}
            MYSQL_DATABASE: ${MYSQL_BLOG_DATABASE}
        ports:
            - "${MYSQL_BLOG_MAPPED_PORT}:3306"
        networks:
            graphite_net:
    php:
        build: ./php  
        container_name: "php"              
        networks: 
            graphite_net:
        volumes:
            - gfiles:/var/www/files
            - ${GRAPHITE_CODE}:/var/www/html
    apache:
        build: ./apache
        container_name: "apache"         
        ports:
            - "8080:80"                  
        volumes:
            - gfiles:/var/www/files
            - ${GRAPHITE_CODE}:/var/www/html      
        networks: 
            graphite_net:
        depends_on:
            - mysql       
            - php
            - memcached      
networks:
    graphite_net:        
volumes:
    gfiles:
